DECLARE @tableName nvarchar(255) = 'INUNDATIONZONES';

SELECT 
	LEFT(CONCAT(TABLE_CATALOG,'.',TABLE_SCHEMA,'.',TABLE_NAME),34) as FullTableName
	,LEFT(COLUMN_NAME,15) as COLUMN_NAME
	,ORDINAL_POSITION
	,IS_NULLABLE
	,LEFT(DATA_TYPE,15) as DATA_TYPE
	,CHARACTER_MAXIMUM_LENGTH
	,NUMERIC_PRECISION
	,NUMERIC_SCALE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = @tableName
ORDER BY ORDINAL_POSITION

